version: '3'
services:
  mongo:
    image: mongo:3.4
    container_name: mongo
    volumes:
      - mongo-volume:/data/db
      - mongo-configdb-volume:/data/configdb

    networks:
      - public

  python:
    image: python
    build: ./python_apps
    container_name: python
    networks:
      - public       


  nginx:
    image: nginx:1.12-alpine
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

    networks:
      - public

volumes:
  mongo-volume:
  mongo-configdb-volume: 


networks:
  public:
    driver: bridge 
